// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi65irRWZz1QhJWmupMIBUJ-PUWA4IAiQ',
    appId: '1:368421980398:web:3a7ee8b0a4d28155194bff',
    messagingSenderId: '368421980398',
    projectId: 'moneytraker-d51b5',
    authDomain: 'moneytraker-d51b5.firebaseapp.com',
    storageBucket: 'moneytraker-d51b5.firebasestorage.app',
    measurementId: 'G-GS42J9K7F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG-xXCl4gT33cM-jAAJq8eygZ8nzHtuvU',
    appId: '1:368421980398:android:d02d732ead18237f194bff',
    messagingSenderId: '368421980398',
    projectId: 'moneytraker-d51b5',
    storageBucket: 'moneytraker-d51b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC377vy0YcLf9P4ZF_Wli2HADOih6mo9w8',
    appId: '1:368421980398:ios:365b20f743b3ed9f194bff',
    messagingSenderId: '368421980398',
    projectId: 'moneytraker-d51b5',
    storageBucket: 'moneytraker-d51b5.firebasestorage.app',
    iosClientId: '368421980398-74ati9ok3hfjm1miut6tgril705m2ve2.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfTraker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC377vy0YcLf9P4ZF_Wli2HADOih6mo9w8',
    appId: '1:368421980398:ios:365b20f743b3ed9f194bff',
    messagingSenderId: '368421980398',
    projectId: 'moneytraker-d51b5',
    storageBucket: 'moneytraker-d51b5.firebasestorage.app',
    iosClientId: '368421980398-74ati9ok3hfjm1miut6tgril705m2ve2.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfTraker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi65irRWZz1QhJWmupMIBUJ-PUWA4IAiQ',
    appId: '1:368421980398:web:5810f41ecf30fc91194bff',
    messagingSenderId: '368421980398',
    projectId: 'moneytraker-d51b5',
    authDomain: 'moneytraker-d51b5.firebaseapp.com',
    storageBucket: 'moneytraker-d51b5.firebasestorage.app',
    measurementId: 'G-FX5NQ73491',
  );
}
